### ISSUE TITLE
Unable to connect my wallet

### ISSUE THREAD

**Issue by akharito1975** [FuelLabs/fuels-wallet#415] opened 2023-01-03 15:39 UTC
### What version of Wallet are you using?

0.0.1

### What is happening?

When applying button CONNECT "Cannot read properties of undefined (reading 'connect')" appears. Wallet does not popup. 

Browser - Chrome, version 108.0.5359.124 
OS MAC OS Ventura 13.0

### steps to reproduce

![2023-01-03_17-35-57](https://user-images.githubusercontent.com/98231941/210390143-78602132-3fe5-4fc2-b690-0c77ec4e858b.png)

### How it should behave?

I expected Pop up wallet extension and connection to it.

### What os are you seeing the problem on?

Mac/Apple Desktop

### What browser?

Chrome

### What is your browser version?

108.0.5359.124

**Comment by matt-user** [comment] 2023-01-06 16:50
closing as duplicate of #411

**Closed by matt-user** 2023-01-06 16:50 UTC
Labels: bug
