### ISSUE TITLE
I can't send ETH

### ISSUE THREAD

**Issue by isuke7528** [FuelLabs/fuels-wallet#614] opened 2023-03-06 15:03 UTC
### What version of Wallet are you using?

FUEL　WALLET　alpha

### What is happening?

When I send 0.2 ETH to my address, an error is displayed and I can't do anything

### steps to reproduce

Just select SEND and send 0.2ETH to your address

### How it should behave?

I want you to send me

### What os are you seeing the problem on?

Windows Desktop

### What browser?

Chrome

### What is your browser version?

バージョン: 110.0.5481.178（Official Build） （64 ビット）

**Comment by LuizAsFight** [comment] 2023-04-19 21:57
closing as duplicate of #613

**Closed by LuizAsFight** 2023-04-19 21:57 UTC
Labels: bug
