### ISSUE TITLE
Add test for loader components

### ISSUE THREAD

**Issue by LuizAsFight** [FuelLabs/fuels-wallet#295] opened 2022-12-01 02:13 UTC
### Motivation

we should write tests for rendering the Loader components as well 

This issue is meant to add a render test to loaders components across the app

```
  it('a11y', async () => {
    await testA11y(<TxHeader.Loader />);
  });
```

**Comment by ef3n9r98** [comment] 2022-12-13 00:24
Hi @LuizAsFight, I know some devs who'd be interested in working on this. Is there a budget for fixing this issue, and if so, how much? 

I'd put this issue up on [OpenQ](http://www.openq.dev/).

Thanks!

**Comment by qqqzhch** [comment] 2023-03-06 13:07
Is it trying to do this?
For example, for the TxHeaderLoader.tsx component, it's a matter of writing TxHeaderLoader.test.tsx and checking the number of svg elements rect

**Comment by LuizAsFight** [comment] 2023-03-06 15:58
> Is it trying to do this? For example, for the TxHeaderLoader.tsx component, it's a matter of writing TxHeaderLoader.test.tsx and checking the number of svg elements rect @LuizAsFight

hi @qqqzhch , thanks for checking...

so the answer is no, we just need to add simple tests to every component that has loader.
`TxHeader.test.tsx` already has it:
```
  it('a11y', async () => {
    await testA11y(<TxHeader {...MOCK_TRANSACTION_SCRIPT} />);
  });

  it('a11y Loader', async () => {
    await testA11y(<TxHeader.Loader />);
  });
```


Notice the second test validating the loader. That's what we need to do to other components as well

**Comment by qqqzhch** [comment] 2023-03-07 01:18
> > Is it trying to do this? For example, for the TxHeaderLoader.tsx component, it's a matter of writing TxHeaderLoader.test.tsx and checking the number of svg elements rect @LuizAsFight
> 
> hi @qqqzhch , thanks for checking...
> 
> so the answer is no, we just need to add simple tests to every component that has loader. `TxHeader.test.tsx` already has it:
> 
> ```
>   it('a11y', async () => {
>     await testA11y(<TxHeader {...MOCK_TRANSACTION_SCRIPT} />);
>   });
> 
>   it('a11y Loader', async () => {
>     await testA11y(<TxHeader.Loader />);
>   });
> ```
> 
> Notice the second test validating the loader. That's what we need to do to other components as well

Okay, I get it, assign this issue to me and I will do this issue while looking at the project code

**Comment by qqqzhch** [comment] 2023-03-09 13:10
@LuizAsFight
When I run npm run test in the app directory, a number of errors are caused by the following
```
  src/systems/Core/machines/fetchMachine.ts:52:31 - error TS2307: Cannot find module './fetchMachine.typegen' or its corresponding type declarations.

    52         tsTypes: {} as import('./fetchMachine.typegen').Typegen0,
```
I don't find a similar file in the documentation, is the latest code base not submitted?

**Comment by LuizAsFight** [comment] 2023-03-10 04:18
@qqqzhch did you try to run `pnpm build:libs` first, then later running `pnpm test`? all in root dir of repo

**Comment by qqqzhch** [comment] 2023-03-10 09:42
@luizstacio   thank you the test is ready to work

**Comment by qqqzhch** [comment] 2023-03-10 10:25
```
cd app/
jest src/systems/Transaction/components/ActivityItem/ActivityItem
attern: src/systems/Transaction/components/ActivityItem/ActivityItem - 0 matches
```
How to run jest on only one file in this project? I tried to pass in the file path, but it didn't work
@luizstacio

**Comment by eswarasai** [comment] 2023-03-10 11:56
> How to run jest on only one file in this project?

@qqqzhch - You can probably use below command, if you're looking to execute all the tests in a single file.

```js
cd packages/app
jest ActivityItem.test.tsx
```

**Comment by LuizAsFight** [comment] 2023-03-10 13:11
you're tagging the wrong Luiz @qqqzhch hahahaha

for testing only a single test, for example: 
`pnpm test:appfile packages/app/src/systems/Account/machines/accountsMachine.test.ts`

**Closed** 2024-01-10 21:20 UTC
